package com.levviata.lspecial;

import net.minecraft.client.gui.GuiScreen;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.common.config.ConfigCategory;
import net.minecraftforge.fml.client.config.GuiConfig;
import net.minecraftforge.fml.client.config.IConfigElement;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import java.io.File;
import java.util.*;

@Mod.EventBusSubscriber(modid = Tags.MOD_ID, value = Side.CLIENT)
public final class LSPECIALConfig {
 private LSPECIALConfig() {}
 public static Configuration config;
 private static final String STATS="1_special_stats", BOB="2_bobbleheads_consumption", GUNS="3_guns_ammunition", POTIONS="4_potions_effects", RECIPES="5_recipes_ore_dictionary", MESSAGES="6_gameplay_messages", CLIENT="7_client_interface", COMMANDS="8_commands_experimental", ADV="9_advanced";
 public static boolean strength=true, perception=true, endurance=true, charisma=true, intelligence=true, agility=true, luck=true, statLimit=true, hideDisabledStats=true;
 public static int statsPerBobblehead=1, potionTimeTicks=115, charismaPotionAmplifier=0, endurancePotionAmplifier=1, bobbleheadUsesPerConsumption=1;
 public static boolean infiniteItemDurability=true, charismaBonus=true, enduranceBonus=true, amplifiedRegeneration=true, respectHigherRegenAmplifier=false, modifyGuns=true, buckshotDelayNerf=true, revolverPerk=true, pepperboxPerk=true, refundMagazines=true, bobbleheadRename=true, hotbarMessages=true, variedAugLimitMessages=true, toggleSpecial=true, setSpeedCommand=true, setFlySpeedCommand=true, nukeFrance=false;
 public static String bobbleheadConsumption="ON_USE", limitMessage="I have reached my limit, I can't consume more.", augLimitMessage="Augmented SPECIAL limit by one", augUnder5="Augmented my SPECIAL limit by one, cool", aug5="Augmented SPECIAL limit by one", aug10="SPECIAL limit++", aug20="Limit++";
 public static double regenAmplifierBonus=1.0, gunWearReductionPerIntelligence=0.05;
 public static String agilityFormula="agility * 0.075", enduranceFormula="endurance", attackDamageFormula="strength", armorFormula="charisma * 2.0", armorToughnessFormula="charisma * 0.5", perceptionGunDamageFormula="perception", bonusDelayFormula="floor(intelligence / 10)", buckshotDelayFormula="originalDelay - floor(intelligence / 100)", gunWearMode="INFINITE_AT_INTELLIGENCE_5", gunWearFormula="min(intelligence * 0.05, 0.75)";
 public static String refundAmmoFormula="min(luck * 0.05, 0.5)";
 public static String buckshotGaugeList="41,42,43,44,45,46,47,48,49,78,79,80,81,84,hbm:ammo_secret:3", revolverList="hbm:gun_flaregun,hbm:gun_heavy_revolver,hbm:gun_light_revolver_atlas,hbm:gun_light_revolver";
 public static boolean[] recipeEnabled={true,true,true,true,true,true,true};
 public static String oreAnyBobblehead="anyBobblehead", oreAppleLead="appleLead", oreAmmo="ammo", oreLuckAccessory="luckAccessory", oreLuckyGem="luckyGem";
 public static String oreAnyBobbleheadEntries="hbm:bobblehead:8-28", oreAppleLeadEntries="hbm:apple_lead:0-2", oreAmmoEntries="hbm:ammo_standard:0-94", oreLuckAccessoryEntries="hbm:bandaid:0,hbm:serum:0,hbm:spider_milk:0,hbm:heart_piece:0,hbm:wd40:0", oreLuckyGemEntries="minecraft:emerald:0,minecraft:diamond:0";
 public static String[] recipeIngredients={"anyBobblehead,hbm:schnitzel_vegan,appleLead,hbm:ingot_u235","anyBobblehead,hbm:weapon_mod_special:1,hbm:weapon_mod_special:6,ammo","anyBobblehead,hbm:med_bag,hbm:crackpipe,potion:healing|strong_healing","anyBobblehead,hbm:cobalt_helmet,hbm:steel_helmet,hbm:titanium_helmet","anyBobblehead,hbm:part_mechanism:34,hbm:circuit:9,hbm:gun_kit_2","anyBobblehead,hbm:cotton_candy,potion:swiftness|long_swiftness|strong_swiftness,minecraft:sugar","anyBobblehead,ammo,luckyGem,luckAccessory"};
 public static void init(File file){ config=new Configuration(file); load(); }
 public static void load(){ if(config==null)return; config.load();
  strength=b(STATS,"strength",true,"Enable Strength"); perception=b(STATS,"perception",true,"Enable Perception"); endurance=b(STATS,"endurance",true,"Enable Endurance"); charisma=b(STATS,"charisma",true,"Enable Charisma"); intelligence=b(STATS,"intelligence",true,"Enable Intelligence"); agility=b(STATS,"agility",true,"Enable Agility"); luck=b(STATS,"luck",true,"Enable Luck"); statLimit=b(STATS,"statLimit",true,"Enforce the SPECIAL stat limit"); hideDisabledStats=b(STATS,"hideDisabledStats",true,"Hide disabled stats in GuiSPECIAL; false strikes them through"); charismaBonus=b(STATS,"charismaBonus",true,"Enable Charisma bonus"); enduranceBonus=b(STATS,"enduranceBonus",true,"Enable Endurance bonus"); infiniteItemDurability=b(STATS,"infiniteItemDurability",true,"Intelligence lesser perk: held damageable items do not lose durability at Intelligence 5+");
  statsPerBobblehead=i(BOB,"statsPerBobblehead",1,1,100,"Points per bobblehead"); bobbleheadConsumption=s(BOB,"consumptionMode","ON_USE","ON_USE, EVERY_X_USES, NEVER"); if(!bobbleheadConsumption.equals("ON_USE") && !bobbleheadConsumption.equals("EVERY_X_USES") && !bobbleheadConsumption.equals("NEVER")) bobbleheadConsumption="ON_USE"; bobbleheadUsesPerConsumption=i(BOB,"usesPerConsumption",1,1,1000000,"Successful uses before consuming item"); bobbleheadRename=b(BOB,"rename",true,"Rename bobblehead tooltip labels"); 
  refundAmmoFormula=s(GUNS,"refundAmmoFormula",refundAmmoFormula,"Validated expression; variable: luck"); modifyGuns=b(GUNS,"modifyGuns",true,"Master switch for gun modifications"); buckshotDelayNerf=b(GUNS,"buckshotDelayNerf",true,"Use the buckshot/automatic delay formula"); revolverPerk=b(GUNS,"revolverHigherPerk",true,"Enable Intelligence revolver perk"); pepperboxPerk=b(GUNS,"pepperboxLesserPerk",true,"Enable Pepperbox lesser perk"); refundMagazines=b(GUNS,"refundMagazines",true,"Enable magazine refunds"); gunWearMode=s(GUNS,"gunWearMode","INFINITE_AT_INTELLIGENCE_5","INFINITE_AT_INTELLIGENCE_5, PERCENT_REDUCTION, FORMULA"); if(!gunWearMode.equals("INFINITE_AT_INTELLIGENCE_5") && !gunWearMode.equals("PERCENT_REDUCTION") && !gunWearMode.equals("FORMULA")) gunWearMode="INFINITE_AT_INTELLIGENCE_5"; gunWearReductionPerIntelligence=d(GUNS,"gunWearReductionPerIntelligence",.05,0,1,"Wear reduction per Intelligence point"); buckshotGaugeList=s(GUNS,"buckshotGaugeList",buckshotGaugeList,"Comma separated ammo metadata values"); revolverList=s(GUNS,"revolverList",revolverList,"Comma separated item registry IDs");
  amplifiedRegeneration=b(POTIONS,"amplifiedRegeneration",true,"Enable amplified regeneration"); respectHigherRegenAmplifier=b(POTIONS,"respectHigherRegenAmplifier",false,"Do not transform vanilla regeneration amplifier > 1"); regenAmplifierBonus=d(POTIONS,"regenAmplifierBonus",1,0,255,"Amplifier bonus"); potionTimeTicks=i(POTIONS,"potionTimeTicks",115,0,720000,"Potion duration in ticks"); charismaPotionAmplifier=i(POTIONS,"charismaPotionAmplifier",0,0,255,"Resistance amplifier"); endurancePotionAmplifier=i(POTIONS,"endurancePotionAmplifier",1,0,255,"Regeneration amplifier bonus");
  hotbarMessages=b(MESSAGES,"hotbarMessages",true,"Show hotbar messages"); limitMessage=s(MESSAGES,"limitMessage",limitMessage,"Stat limit reached message"); variedAugLimitMessages=b(MESSAGES,"variedAugLimitMessages",true,"Use tiered augLimit messages"); augLimitMessage=s(MESSAGES,"augLimitMessage","Augmented SPECIAL limit by one","Single augLimit message"); augUnder5=s(MESSAGES,"augUnder5",augUnder5,"Original message below 5"); aug5=s(MESSAGES,"aug5",aug5,"Original message at 5+"); aug10=s(MESSAGES,"aug10",aug10,"Original message at 10+"); aug20=s(MESSAGES,"aug20",aug20,"Original message at 20+");
  toggleSpecial=b(CLIENT,"toggleSpecial",true,"Enable toggleSpecial keybind"); setSpeedCommand=b(COMMANDS,"setSpeedCommand",true,"Register /setspeed"); setFlySpeedCommand=b(COMMANDS,"setFlySpeedCommand",true,"Register /setflyspeed"); nukeFrance=b(COMMANDS,"nukeFrance",false,"Dummy joke option; no gameplay effect");
  String[] rn={"recipe1","recipe2","recipe3","recipe4","recipe5","recipe6","recipe7"}; for(int n=0;n<7;n++) recipeEnabled[n]=b(RECIPES,rn[n],true,"Enable bobblehead recipe "+(n+1));
  oreAnyBobblehead=s(RECIPES,"oreAnyBobblehead","anyBobblehead","Ore dictionary name"); oreAppleLead=s(RECIPES,"oreAppleLead","appleLead","Ore dictionary name"); oreAmmo=s(RECIPES,"oreAmmo","ammo","Ore dictionary name"); oreLuckAccessory=s(RECIPES,"oreLuckAccessory","luckAccessory","Ore dictionary name"); oreLuckyGem=s(RECIPES,"oreLuckyGem","luckyGem","Ore dictionary name"); oreAnyBobbleheadEntries=s(RECIPES,"oreAnyBobbleheadEntries",oreAnyBobbleheadEntries,"namespace:item:metadata or namespace:item:start-end, comma separated"); oreAppleLeadEntries=s(RECIPES,"oreAppleLeadEntries",oreAppleLeadEntries,"Ore dictionary entries"); oreAmmoEntries=s(RECIPES,"oreAmmoEntries",oreAmmoEntries,"Ore dictionary entries"); oreLuckAccessoryEntries=s(RECIPES,"oreLuckAccessoryEntries",oreLuckAccessoryEntries,"Ore dictionary entries"); oreLuckyGemEntries=s(RECIPES,"oreLuckyGemEntries",oreLuckyGemEntries,"Ore dictionary entries");
  for(int n=0;n<7;n++) recipeIngredients[n]=s(RECIPES,"recipe"+(n+1)+"Ingredients",recipeIngredients[n],"Comma-separated tokens: oreName, namespace:item[:meta], potion:type|type");
  agilityFormula=s(ADV,"agilityFormula",agilityFormula,"Expression variable: agility"); enduranceFormula=s(ADV,"enduranceFormula",enduranceFormula,"Expression variable: endurance"); attackDamageFormula=s(ADV,"attackDamageFormula",attackDamageFormula,"Expression variable: strength"); armorFormula=s(ADV,"armorFormula",armorFormula,"Expression variable: charisma"); armorToughnessFormula=s(ADV,"armorToughnessFormula",armorToughnessFormula,"Expression variable: charisma"); perceptionGunDamageFormula=s(ADV,"perceptionGunDamageFormula",perceptionGunDamageFormula,"Variables: perception, originalDamage"); bonusDelayFormula=s(ADV,"bonusDelayFormula",bonusDelayFormula,"Variables: intelligence, originalDelay; floor preserves the original integer step"); buckshotDelayFormula=s(ADV,"buckshotDelayFormula",buckshotDelayFormula,"Variables: intelligence, originalDelay"); gunWearFormula=s(ADV,"gunWearFormula",gunWearFormula,"Variables: intelligence, originalWear; output is reduction fraction");
  for(String c:Arrays.asList(STATS,BOB,GUNS,POTIONS,RECIPES,MESSAGES,CLIENT,COMMANDS,ADV)) config.setCategoryComment(c,categoryComment(c)); if(config.hasChanged())config.save();
 }
 private static String categoryComment(String c){ if(c.equals(ADV))return "Arithmetic expressions support + - * / %, parentheses, variables, min/max/abs/sqrt/floor/ceil/round."; if(c.equals(POTIONS))return "Potion duration values are measured in ticks."; if(c.equals(CLIENT))return "Client-only GUI and keybind settings."; if(c.equals(MESSAGES))return "Gameplay feedback messages."; if(c.equals(BOB))return "Bobblehead item behavior and stat progression."; if(c.equals(GUNS))return "Gun mechanics, perks, ammunition and durability."; if(c.equals(RECIPES))return "Recipe switches and ore dictionary configuration."; if(c.equals(COMMANDS))return "Optional commands and harmless experimental options."; return "LSPECIAL mod configuration."; }
 private static boolean b(String c,String k,boolean d,String m){return config.get(c,k,d,m).getBoolean(d);} private static int i(String c,String k,int d,int min,int max,String m){return config.get(c,k,d,m,min,max).getInt(d);} private static double d(String c,String k,double def,double min,double max,String m){return config.get(c,k,def,m,min,max).getDouble(def);} private static String s(String c,String k,String def,String m){return config.get(c,k,def,m).getString();}
 @SubscribeEvent public static void changed(ConfigChangedEvent.OnConfigChangedEvent e){if(Tags.MOD_ID.equals(e.getModID()))load();}
 @SideOnly(Side.CLIENT) public static GuiScreen gui(GuiScreen parent){List<IConfigElement> list=new ArrayList<>();for(String n:Arrays.asList(STATS,BOB,GUNS,POTIONS,RECIPES,MESSAGES,CLIENT,COMMANDS,ADV)){ConfigCategory c=config.getCategory(n);list.add(new ConfigElement(c));}return new GuiConfig(parent,list,Tags.MOD_ID,false,false,Tags.MOD_NAME+" Configuration");}
}
